### ISSUE TITLE
il2cpp error with Unity 2021.3

### ISSUE THREAD

**Issue by denravonska** [louthy/language-ext#1187]
When building Unity projects which use the il2cpp backend the build fails when trying to convert `EitherUnsafe`

```
Error: IL2CPP error for method 'LanguageExt.EitherUnsafe`2<R,L> LanguageExt.EitherUnsafe`2::Swap()' in assembly 'C:\Users\linus\Documents\Zyax-Repos\MachineControl\Library\Bee\artifacts\Android\ManagedStripped\LanguageExt.Core.dll'
System.NotImplementedException: No support for assigning to/from variable size types of different types LanguageExt.EitherUnsafe`2<R,L>, LanguageExt.EitherUnsafe`2<L,R>
   at Unity.IL2CPP.MethodBodyWriter.GetAssignment(ReadOnlyContext context, String leftName, ResolvedTypeInfo leftType, StackInfo right, VariableSizedTypeSupport variableSizedTypeSupport, SharingType sharingType)
   at Unity.IL2CPP.MethodBodyWriter.WriteStloc(ResolvedVariable variableDefinition)
   at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction(Node node, InstructionBlock block, ResolvedInstruction ins)
   at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive(Node node, ReadOnlyDictionary`2 instructionBlocks)
   at Unity.IL2CPP.MethodBodyWriter.Generate()
   at Unity.IL2CPP.CodeWriters.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef, Boolean writingMethodBody)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(AssemblyWriteContext context, IGeneratedMethodCodeWriter writer, MethodReference method)
   at Unity.IL2CPP.SourceWriter.WriteTypesMethods(SourceWritingContext context, IGeneratedMethodCodeWriter writer, TypeWritingInformation& writingInformation, NPath filePath, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.WriteItem(StreamWorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

I don't know if this is an il2cpp or a language-ext problem but I'm starting here :)
Any idea what could cause this and if there's a fix/workaround?

Tested with:

 - Unity 2021.3.16f1 and 2021.3.18f1
 - LanguageExt.Core 4.4.0 and 4.4.2

**Comment by louthy** [comment]
That's not an error thrown by language-ext, so I assume it's an issue with Unity.

This line looks suspicious though: 

```
 No support for assigning to/from variable size types of different types LanguageExt.EitherUnsafe`2<R,L>, LanguageExt.EitherUnsafe`2<L,R>
```

`R, L` is the wrong way around, it should be `L, R`.  So I don't know if this is just a regular coding error where you've got the parameters the wrong way around?  There's no code to examine, so I can't tell.

**Comment by denravonska** [comment]
We don't actually use that, at least not directly in our code. So far we only use

- `HashMap`
- `Seq`
- `Filter`/`Iter` etc

This is when, I assume, il2cpp generates cpp from IL. The problem is most likely there so I'll fish in the Unity issue tracker.

**Comment by denravonska** [comment]
Regarding L/R vs R/L it looks very intentional, 7c981e87cad20ae09ce654dedb3452d84f6def7f

**Comment by denravonska** [comment]
Closing this as it's most likely an il2cpp error. I tested this with a local fork which has the swaps commented out. It builds, to a degree, but the build process exhausts all memory on all machines we can throw at it.
