### ISSUE TITLE
Method returning null for a Option<{nullable object}> returns Some with an empty nullable object.

### ISSUE THREAD

**Issue by Orca2040** [louthy/language-ext#229]
When a method is written returning an Option for a nullable object like int? or short?, the method returns a nullable object with a null value instead of a None.
Code
```
public static void Run()
{
    var nullShort = nullableShort();
    var nullInt = nullableInt();
    match(
        nullShort,
        x => Console.WriteLine($"Value is: {x}"),
        () => Console.WriteLine("Null"));
    match(
        nullInt,
        x => Console.WriteLine($"Value is: {x.Value}"),
        () => Console.WriteLine("Null"));
}

public static Option<short?> nullableShort()
{
    return null;
}

public static Option<int?> nullableInt()
{
    return null;
}

```
Output
```
Value is:

Unhandled Exception: System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at MonadTestProject.Program.<>c.<Run>b__2_2(Nullable`1 x) in C:\Users\aordonez\Documents\Visual Studio 2013\Projects\MonadTestProject\MonadTestProject\Program.cs:line 37
   at LanguageExt.ClassInstances.MOption`1.Match(Option`1 opt, Action`1 Some, Action None)
   at LanguageExt.Option`1.Match(Action`1 Some, Action None)
   at LanguageExt.Prelude.match[T](Option`1 option, Action`1 Some, Action None)
   at MonadTestProject.Program.Run() in C:\Users\aordonez\Documents\Visual Studio 2013\Projects\MonadTestProject\MonadTestProject\Program.cs:line 35
   at MonadTestProject.Program.Main(String[] args) in C:\Users\aordonez\Documents\Visual Studio 2013\Projects\MonadTestProject\MonadTestProject\Program.cs:line 11
```

**Comment by louthy** [comment]
@Orca2040 There's no implicit coercion for nullable types in case the behaviour you're describing is intentional.  `Nullable` is a `struct`, so when you return `null` it's creating a `Nullable<T>` which isn't `null`.  And so `Option` happily wraps it up.

It does seem a little strange that you want to maintain the nullable type but remove its one additional feature over the value type it wraps: it's nullability.  So if you want it to not be `null` then return `Option<int>` and `Option<short>` rather than `Option<int?>` and `Option<short?>`.

You can use the explicit coercion of `Optional(x)`:
```c#
        public static Option<short> nullableShort()
        {
            short? x = null;
            return Optional(x);
        }

        public static Option<int> nullableInt()
        {
            int? x = null;
            return Optional(x);
        }
```
Or use `Some(x)` which will throw a `ValueIsNullException` if the nullable is `null`.

**Comment by Orca2040** [comment]
In a new project I'm working on we are using EntityFramework with a database first implementation and they chose to keep `Nullable` types as the database is quite old. When I came across this with `Nullable`, I wasn't sure if this was the intended usage. Thank you for clarifying, my usage was just odd and didn't realize I should be returning `Nullable`
