### ISSUE TITLE
Set(unit, unit); throws an exception

### ISSUE THREAD

**Issue by StanJav** [louthy/language-ext#252]
At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at LanguageExt.ClassInstances.OrdDefault`1.Compare(A x, A y)
   at LanguageExt.SetModule.TryAdd[OrdK,K](SetItem`1 node, K key)
   at LanguageExt.SetInternal`2..ctor(IEnumerable`1 items, Boolean tryAdd)
   at LanguageExt.Set`1..ctor(IEnumerable`1 items)
   at LanguageExt.Set.createRange[T](IEnumerable`1 range)
   at LanguageExt.Prelude.Set[T](T head, T[] tail)

**Comment by louthy** [comment]
Fixed in v2.1.18
