### ISSUE TITLE
Removing an item from a list throws Argument exception when value does not implement IComparable

### ISSUE THREAD

**Issue by bradphelan** [louthy/language-ext#284]
Following test case

        [Fact]
        public void ListShouldRemoveByReference()
        {
            var o0 = new Object();
            var o1 = new Object();
            var l = List( o0, o1 );
            l = l.Remove( o0 );
            l.Count.Should().Be( 1 );

        }

Now given that Lst<A> doesn't prescribe any ordering constraint I'm surprised that remove causes this exception. Error is
```

System.ArgumentException : At least one object must implement IComparable.
   at System.Collections.Comparer.Compare(Object a, Object b)
   at LanguageExt.ListModule.Find[T](ListItem`1 node, T key, Int32 index, Int32 count, IComparer`1 comparer)
   at LanguageExt.LstInternal`1.Remove(A value, IComparer`1 equalityComparer)
   at LanguageExt.Lst`1.Remove(A value)
   at Utils.Spec.LanguageExtRecords.ListShouldRemoveByReference()
```

**Comment by louthy** [comment]
Fixed in `v2.1.24` on nu-get now.  NOTE: `Remove` will remove all matches rather than just the first one.
