### ISSUE TITLE
GetHashCode fail with "Sequence contains no elements"

### ISSUE THREAD

**Issue by lucascebertin** [louthy/language-ext#316]
When a class extends from Record<T> and have an ICollection<> (or possible other Generic list) property, calling GetHashCode result in IL, at the line 396, trying to lookup for an "GetHashCode" method.

Looks like the problem is with the Where/Where/Head chain, there is no GetHashCode inside the ICollection and the hash fail with an exception.

To reproduce it I changed some tests like "DeepEqualityTestFieldsAndProperties" in "RecordTypeTests" and added a property like this one on the class "TestClass":
`public ICollection<int> ZZ;`

Stack trace:
 `` at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LanguageExt.List.head[T](IEnumerable`1 list) in C:\tests\language-ext\LanguageExt.Core\DataTypes\List\Lst.Module.cs:line 123
   at ListExtensions.Head[T](IEnumerable`1 list) in C:\tests\language-ext\LanguageExt.Core\DataTypes\List\Lst.Extensions.cs:line 68
   at LanguageExt.IL.<>c__DisplayClass10_0`1.<<GetHashCode>g__Fields|1>d.MoveNext() in C:\tests\language-ext\LanguageExt.Core\Utility\IL.cs:line 396
   at LanguageExt.List.fold[S,T](IEnumerable`1 list, S state, Func`3 folder) in C:\tests\language-ext\LanguageExt.Core\DataTypes\List\Lst.Module.cs:line 371
   at ListExtensions.Fold[S,T](IEnumerable`1 list, S state, Func`3 folder) in C:\tests\language-ext\LanguageExt.Core\DataTypes\List\Lst.Extensions.cs:line 358
   at LanguageExt.IL.GetHashCode[A]() in C:\tests\language-ext\LanguageExt.Core\Utility\IL.cs:line 436
   at LanguageExt.RecordType`1..cctor() in C:\tests\language-ext\LanguageExt.Core\DataTypes\Record\RecordUtil.cs:line ``

**Comment by louthy** [comment]
Fixed in `v2.2.6-beta`

**Comment by lucascebertin** [comment]
Great, thanks!
