### ISSUE TITLE
RecordType comparison broken since 3.0.31

### ISSUE THREAD

**Issue by StanJav** [louthy/language-ext#547]
```
        public class MyRecord : Record<MyRecord>
        {
            public MyRecord()
            {
            }
        }

        var equals = x == x; <--- throws
```

Exception: `CompileToMethod cannot compile constant 'Test.Program+MyRecord' 
because it is a non-trivial value, such as a live object. 
Instead, create an expression tree that can construct this value.`

The above example works with 3.0.28 and throws an exception with 3.0.31 

StackTrace: 
``` 
at System.Linq.Expressions.Compiler.BoundConstants.EmitConstant(LambdaCompiler lc, Object value, Type type)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstant(Object value, Type type)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstantExpression(Expression expr)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(BinaryExpression b)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(Expression expr)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison(Boolean branch, BinaryExpression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAndBranch(Boolean branchValue, Expression node, Label label)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(BinaryExpression b)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(BinaryExpression b)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(BinaryExpression b)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitAndAlsoBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedOrElse(BinaryExpression b)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitOrElseBinaryExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, MethodBuilder method, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.LambdaExpression.CompileToMethodInternal(MethodBuilder method, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.LambdaExpression.CompileToMethod(MethodBuilder method)
   at LanguageExt.IL.Compile[F](LambdaExpression lambda, String typeName, String methodName)
   at LanguageExt.IL.Equals[A](Boolean includeBase)
   at LanguageExt.RecordType`1..cctor()`
```

**Comment by bender2k14** [comment]
This is a duplicate of #530

**Comment by StanJav** [comment]
Ah... yes, thanks @bender2k14  . I will close this one.
